export type Lang = "pt" | "en";
export type Audience = "brazil-us" | "brazil" | "international";

export const copy = {
  pt: {
    home: "Voltar ao site", language: "Idioma da página", skip: "Ir para o conteúdo", progress: "Etapas do agendamento",
    steps: ["Você", "Experiência", "Agenda", "Confirmação"], back: "Voltar", edit: "Alterar", next: "Continuar", online: "100% online", free: "Consulta gratuita", minutes: "60 minutos", noPayment: "Sem pagamento. Sem compromisso.",
    hero: { kicker: "NUTRIÇÃO SEM FRONTEIRAS", title: "Sua vida, mais leve.", accent: "Do seu jeito.", text: "Uma hora gratuita com a Bruna, do seu jeito.", prompt: "Onde começa sua história?", hint: "Assim, a experiência já começa do seu jeito.", signature: "Nutricionista • CRN 20101459", small: "Sua comida. Sua cultura. Seu ritmo.", bottom: "Você não precisa ter tudo resolvido para começar." },
    audiences: [
      { id: "brazil-us", title: "Brasileira(o) nos EUA", detail: "Suas raízes. Sua nova rotina.", symbol: "BR → US" },
      { id: "brazil", title: "Moro no Brasil", detail: "Perto de você, em português.", symbol: "BR" },
      { id: "international", title: "I prefer English", detail: "Personal, one-to-one care.", symbol: "EN" },
    ],
    welcome: "ESTE ESPAÇO É SEU", start: "Ver horários disponíveis", consultTitle: "Vamos começar por você.", consultText: "60 minutos com a Bruna para entender seu momento e descobrir como o acompanhamento pode ajudar.",
    consultItems: ["Sua rotina, sem julgamentos.", "Um cuidado que cabe na sua vida.", "Clareza para o próximo passo."],
    includedKicker: "SE VOCÊ DECIDIR CONTINUAR", includedTitle: "Você não precisa ir sozinha(o).", includedNote: "Plano, app e grupo fazem parte da consultoria contratada. Conheça as opções na sua hora gratuita.",
    proofKicker: "HISTÓRIAS QUE APROXIMAM", proofTitle: "Ela também deu o primeiro passo.", proofText: "Ouça uma cliente da Bruna contar a própria experiência. Talvez você se reconheça no primeiro passo dela.", proofLabel: "Depoimento de uma cliente", proofSource: "Ver depoimento original", proofLang: "Depoimento em português", play: "Reproduzir depoimento da cliente", videoError: "Não foi possível reproduzir aqui. Veja o depoimento no Instagram.",
    faqTitle: "Pode vir com dúvidas.", faqs: [
      ["A consulta de 1 hora é mesmo gratuita?", "Sim. Essa primeira conversa é gratuita, online e sem compromisso de contratar um plano. Você conhece a Bruna, fala sobre sua rotina e tira suas dúvidas."],
      ["Preciso contratar um plano para participar?", "Não. A conversa é um espaço para entender suas necessidades e conhecer o acompanhamento. Você decide se quer continuar depois."],
      ["O plano alimentar está incluído nessa hora?", "Não. O plano individual e o acompanhamento fazem parte da consultoria contratada. A hora gratuita serve para entender seu momento e conversar sobre os próximos passos."],
      ["Como funciona para quem mora fora do Brasil?", "O atendimento é online. Escolha seu idioma de preferência. A Bruna confirma o formato de atendimento adequado para você; na agenda, confira o fuso antes de reservar."],
    ],
    detailsKicker: "SUA CONSULTA GRATUITA", detailsTitle: "Um pouco sobre você.", detailsText: "Só falta confirmar seus dados.", name: "Como podemos chamar você?", namePlaceholder: "Seu nome", email: "E-mail para a confirmação", emailPlaceholder: "voce@exemplo.com", region: "Cidade e estado onde você mora", regionPlaceholder: "Ex.: Orlando, Flórida", spoken: "Idioma de preferência para a conversa", portuguese: "Português", english: "Inglês", goal: "O que você gostaria de tornar mais leve?", optional: "opcional", goals: ["Minha rotina alimentar", "Minhas escolhas no mercado", "Minha relação com a comida", "Quero entender o acompanhamento"],
    detailsCta: "Confirmar minha hora gratuita", detailsNote: "Seus dados serão usados para organizar esta consulta. Não é necessário informar dados de saúde neste formulário.", required: "Preencha seu nome e um e-mail válido. Se informar telefone, inclua o código do país.",
    summaryKicker: "UM TEMPO SÓ SEU", summaryTitle: "Você + Bruna.", summaryText: "Uma conversa com espaço para ouvir, entender e começar.", summaryItems: ["Consulta inicial gratuita", "1 hora, por videochamada", "Sem obrigação de contratar"], summaryFoot: "O próximo passo pode ser simples.",
    calendarKicker: "SEU NOVO COMEÇO", calendarTitle: "Encontre um tempo para você.", calendarText: "Confira o fuso horário, escolha uma data e conclua a reserva na agenda da Bruna.", calendarFrame: "Agenda de consultas da Bruna Tinoco", calendarOpen: "Abrir agenda em uma nova aba", calendarHelp: "Se a agenda não carregar, abra o link abaixo.", calendarNote: "Sua consulta estará marcada quando a agenda mostrar a confirmação. Confira também o e-mail informado.", loading: "Carregando a agenda…", unavailableTitle: "Vamos encontrar seu horário.", unavailableText: "A agenda online está sendo preparada. Você pode falar diretamente com a Bruna para combinar sua hora gratuita.", contact: "Combinar minha consulta no WhatsApp", contactNote: "O WhatsApp abre com sua solicitação. O horário só fica reservado após a confirmação da Bruna.", prepared: "Seu pedido, do seu jeito", shareNote: "Ao abrir o WhatsApp, os dados abaixo serão incluídos na mensagem. Você pode revisá-la antes de enviar.",
    footer: "Nutrição com espaço para a sua vida.", help: "Falar com a Bruna", reset: "Recomeçar", tinyStep: "Um passo de cada vez.",
  },
  en: {
    home: "Back to website", language: "Page language", skip: "Skip to content", progress: "Booking steps",
    steps: ["You", "The experience", "Calendar", "Confirmation"], back: "Back", edit: "Change", next: "Continue", online: "Fully online", free: "Free consultation", minutes: "60 minutes", noPayment: "No payment. No commitment.",
    hero: { kicker: "NUTRITION WITHOUT BORDERS", title: "Feel more at home.", accent: "In your own life.", text: "A free hour with Bruna. Care that fits your life.", prompt: "Where does your story begin?", hint: "Let’s make this experience feel like you.", signature: "Brazilian nutritionist • CRN 20101459", small: "Your food. Your culture. Your pace.", bottom: "You don’t need to have it all figured out to begin." },
    audiences: [
      { id: "brazil-us", title: "Brazilian in the U.S.", detail: "Your roots. Your new routine.", symbol: "BR → US" },
      { id: "brazil", title: "I live in Brazil", detail: "Close to you, in Portuguese.", symbol: "BR" },
      { id: "international", title: "I prefer English", detail: "Personal, one-to-one care.", symbol: "EN" },
    ],
    welcome: "YOU BELONG HERE", start: "See available times", consultTitle: "Let’s start with you.", consultText: "60 minutes with Bruna to talk about where you are now and explore how nutrition support could fit your life.",
    consultItems: ["Your routine, without judgment.", "Explore care that fits your life.", "A clear next step, at your pace."],
    includedKicker: "IF YOU CHOOSE TO CONTINUE", includedTitle: "A little support goes a long way.", includedNote: "Meal plans, the app, and ongoing support are part of the paid program. Explore your options in your free hour.",
    proofKicker: "REAL PEOPLE. REAL STORIES.", proofTitle: "She started with a conversation.", proofText: "Hear a Bruna client share her experience in her own words. Every journey is personal; yours starts with a conversation.", proofLabel: "A client’s experience", proofSource: "Watch the original testimonial", proofLang: "Client video in Portuguese", play: "Play the client testimonial", videoError: "Unable to play the video here. Watch it on Instagram.",
    faqTitle: "Questions are welcome.", faqs: [
      ["Is the one-hour consultation really free?", "Yes. This first conversation is free, online, and comes with no commitment to a plan. Meet Bruna, talk about your routine, and ask your questions."],
      ["Do I have to sign up for a program?", "No. This is a chance to understand your needs and explore the support available. You decide whether to continue afterward."],
      ["Will I receive a meal plan during this hour?", "No. A personal meal plan and ongoing support are part of the paid coaching program. Your free hour is for discussing your needs and possible next steps."],
      ["Can I book an English consultation?", "Yes. Bruna offers private, one-to-one consultations in English. This path focuses on your individual support, without joining Brazilian groups. Check your local time zone in the calendar before booking."],
    ],
    detailsKicker: "YOUR FREE CONSULTATION", detailsTitle: "A little about you.", detailsText: "Just your details, then you’re done.", name: "What should we call you?", namePlaceholder: "Your name", email: "Email for your confirmation", emailPlaceholder: "you@example.com", region: "Your city and state", regionPlaceholder: "e.g. Orlando, Florida", spoken: "Preferred language for the conversation", portuguese: "Portuguese", english: "English", goal: "What would you like to make easier?", optional: "optional", goals: ["My everyday eating routine", "My grocery choices", "My relationship with food", "Understanding the program"],
    detailsCta: "Confirm my free hour", detailsNote: "Your details will be used to arrange this consultation. You don’t need to share any medical information in this form.", required: "Enter your name and a valid email. If adding a phone number, include its country code.",
    summaryKicker: "A LITTLE TIME JUST FOR YOU", summaryTitle: "You + Bruna.", summaryText: "A conversation with room to listen, understand, and begin.", summaryItems: ["Free initial consultation", "One hour, by video call", "No obligation to join a program"], summaryFoot: "Your next step can be simple.",
    calendarKicker: "YOUR FRESH BEGINNING", calendarTitle: "Make a little room for you.", calendarText: "Check your time zone, choose a date, and complete your booking in Bruna’s calendar.", calendarFrame: "Bruna Tinoco consultation calendar", calendarOpen: "Open the calendar in a new tab", calendarHelp: "If the calendar doesn’t load, open the link below.", calendarNote: "Your consultation is booked when the calendar displays a confirmation. Check the email address you provided, too.", loading: "Loading the calendar…", unavailableTitle: "Let’s find your time.", unavailableText: "The online calendar is being prepared. You can contact Bruna directly to arrange your free hour.", contact: "Arrange my consultation on WhatsApp", contactNote: "WhatsApp opens with your request. Your time is reserved only after Bruna confirms it.", prepared: "Your personal request", shareNote: "Opening WhatsApp includes the details below in your message. You can review it before sending.",
    footer: "Nutrition with room for your life.", help: "Talk to Bruna", reset: "Start again", tinyStep: "One step at a time.",
  },
} as const;

export const pathways = {
  "brazil-us": {
    pt: { label: "BRASIL NO CORAÇÃO. VIDA NOS EUA.", title: "Seu jeito brasileiro.", accent: "Sua vida nos EUA.", text: "Arroz, feijão, uma rotina corrida e um mercado diferente. Seu cuidado pode respeitar tudo isso, em português.", features: [["Comida que faz sentido", "Orientação sobre produtos, rótulos e substituições nos mercados americanos."], ["Seu plano, sempre por perto", "Aplicativo do paciente para consultar seu plano e organizar a rotina."], ["Acolhimento em português", "Suporte e grupo no WhatsApp para ter companhia no processo."]] },
    en: { label: "BRAZIL AT HEART. LIFE IN THE U.S.", title: "Your Brazilian roots.", accent: "Your American routine.", text: "Rice, beans, a busy schedule, and a different grocery store. Your nutrition support can make room for all of it, in Portuguese.", features: [["Food that fits your life", "Guidance on U.S. grocery products, labels, and practical swaps."], ["Your plan, close at hand", "A patient app to access your plan and organize your routine."], ["Connection in Portuguese", "WhatsApp support and a group to share the journey with."]] },
  },
  brazil: {
    pt: { label: "PERTO DE VOCÊ, ONDE VOCÊ ESTIVER", title: "Sua comida de sempre.", accent: "Um novo cuidado.", text: "O almoço em família, o café da tarde, a correria da semana. Uma alimentação possível começa na vida que você já tem.", features: [["Sua rotina no centro", "Plano individual com alimentos que você conhece e encontra perto de casa."], ["Seu plano na palma da mão", "Aplicativo do paciente para acessar orientações no seu dia a dia."], ["Você tem com quem contar", "Suporte e grupo no WhatsApp, com acolhimento em português."]] },
    en: { label: "CLOSE TO YOU, WHEREVER YOU ARE", title: "Your familiar foods.", accent: "A fresh approach.", text: "Family lunches, afternoon coffee, and full weeks. A realistic way of eating begins with the life you already have.", features: [["Your routine comes first", "A personal plan with familiar foods available close to home."], ["Your plan in your pocket", "A patient app to keep guidance close throughout your day."], ["Someone in your corner", "WhatsApp support and a group, with care in Portuguese."]] },
  },
  international: {
    pt: { label: "UM CUIDADO QUE COMEÇA COM ESCUTA", title: "Sua história é única.", accent: "Seu cuidado também.", text: "Você é bem-vindo aqui. Compartilhe onde mora e seu idioma de preferência para conhecer o formato de acompanhamento com a Bruna.", features: [["Sua vida, de verdade", "Uma conversa sobre seus horários, preferências e hábitos."], ["Clareza antes de começar", "Entenda os formatos e recursos disponíveis para seu local e idioma."], ["Um próximo passo possível", "Converse sobre um acompanhamento que faça sentido para você."]] },
    en: { label: "PRIVATE SUPPORT. A PERSONAL CONNECTION.", title: "Your life. Your goals.", accent: "Your time with Bruna.", text: "One-to-one, in English. Make room for food you love and support that understands your everyday life.", features: [["One-to-one attention", "Your own space to talk about your routine, preferences, and goals with Bruna."], ["A conversation in English", "Understand your options clearly, with time for the questions that matter to you."], ["Support at your pace", "Explore individual follow-up focused on your life, without joining a group."]] },
  },
} as const;
